### ISSUE TITLE
I always get the following error, why?

### ISSUE THREAD

**Issue by ihelloz** [dobraczek/this-person-does-not-exist.com#1]
Traceback (most recent call last):
  File "/Users/helloz/Downloads/download.py", line 31, in <module>
    data  = json.loads(webpage.decode('utf-8'))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ihelloz** [comment]
Fix:
`request_site = Request("https://this-person-does-not-exist.com/new?time=" + str(n_date) + "&gender=" + n_gender + "&age=" + n_age + "&etnic=" + n_entit, headers={"User-Agent": "Mozilla/5.0"})`
